### ISSUE TITLE
simplify lexer

### ISSUE THREAD

**Issue by maddanio** [Bobbias/unnamed-compiler#2]
sorry, this is not meant as critique, but I would like to make the lexer streaming as well and make it independen from the compiler, basically just work on an arbitrary character stream. also I think number tokens should be stored as strings. the jakt selfhost also moved there because parsing them too early can lead to problems. just let me know if that makes sense for you then I will see to make a PR. really like this project :)

**Comment by maddanio** [comment]
i hacked my way through in my fork https://github.com/maddanio/unnamed-compiler, i feel I also fixed some things, not sure. it parses some small jakt code, but chokes on something big like the selfhosted parser. jsut an experiment :)

**Comment by maddanio** [comment]
actually it ran into an infinite loop, fixing things in the parser but it already parses the first 40k of typechecker.jakt in 0.5s :)

**Comment by Bobbias** [comment]
After merging PRs #1 and #3, I think we can close this issue :^)
